name: Windows Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:

    runs-on: "windows-latest"
    strategy:
      matrix:
        python-version:
          - "2.7"

    steps:
    - name: Check out source code
      uses: actions/checkout@v2
      with:
        # Get enough history for the tags we get next to be meaningful.  0
        # means all history.
        fetch-depth: "0"
    # Get tags not fetched by the checkout action, needed for auto-versioning.
    - run: "git fetch origin +refs/tags/*:refs/tags/*"

    # Get MS VC++ 9 aka Visual Studio 2008, required to build Python 2.7
    # extensions (zfec via Tahoe-LAFS).
    - name: Build local chocloatey package for MSVC 9.0 for Python 2.7
      uses: "crazy-max/ghaction-chocolatey@v1"
      with:
        args: "pack .github/vcpython27/vcpython27.nuspec"

    - name: Install MSVC 9.0 for Python 2.7
      uses: "crazy-max/ghaction-chocolatey@v1"
      with:
        args: "install --source=.;https://chocolatey.org/api/v2/ vcpython27"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Use pip cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel tox

    - name: Test with tox
      run: tox -e py27-coverage
      env:
        MAGIC_FOLDER_HYPOTHESIS_PROFILE: "magic-folder-ci"
        PIP_FIND_LINKS: ./wheelhouse

    - name: Upload eliot.log in case of failure
      uses: "actions/upload-artifact@v2"
      with:
        if-no-files-found: "warn"
        name: "eliot.log"
        path: "eliot.log"

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: "322d708d-8283-4827-b605-ccf02bfecf70"
        file: "./coverage.xml"
